# Generated by Django 6.0.6 on 2026-06-20 20:59

import apps.appeals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='Регистрационный номер')),
                ('citizen_full_name', models.CharField(max_length=200, verbose_name='ФИО гражданина')),
                ('citizen_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('citizen_address', models.CharField(max_length=500, verbose_name='Адрес проживания')),
                ('citizen_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('category', models.CharField(choices=[('housing', 'ЖКХ'), ('transport', 'Транспорт'), ('social', 'Соцзащита'), ('education', 'Образование'), ('ecology', 'Экология'), ('other', 'Прочее')], max_length=20, verbose_name='Категория')),
                ('subject', models.CharField(max_length=300, verbose_name='Тема обращения')),
                ('text', models.TextField(verbose_name='Текст обращения')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('assigned', 'Назначено'), ('in_progress', 'В работе'), ('on_site', 'Выезд'), ('done', 'Исполнено'), ('declined', 'Отказ'), ('closed', 'Закрыто')], default='new', max_length=20, verbose_name='Статус')),
                ('resolution_text', models.TextField(blank=True, verbose_name='Текст решения/ответа')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок исполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppealFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.appeals.models.appeal_file_upload_path, verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Исходное имя файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Файл обращения',
                'verbose_name_plural': 'Файлы обращений',
            },
        ),
        migrations.CreateModel(
            name='AppealHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=500, verbose_name='Действие')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Запись истории',
                'verbose_name_plural': 'История изменений',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
    ]
